### ISSUE TITLE
Krill 0.13.0 RC2 UI does not permit creating ROAs for ipv4 /32

### ISSUE THREAD

**Issue by jayb-github** [NLnetLabs/krill-ui#32]
My attempts to create ipv4 /32 ROAs via the web UI on Krill 0.13.0 RC2 have failed, using both firefox and chromium, both on Linux.
![krill-hates-slash32-firefox](https://user-images.githubusercontent.com/27710839/235013280-d80285a8-0d24-4b55-9bfb-026b74552680.png)
![krill-hates-slash32-chromium](https://user-images.githubusercontent.com/27710839/235013291-facd9c5d-2a18-4757-af33-f633705a3b50.png)

**Comment by jayb-github** [comment]
I verified that I was able to create an ipv4 /32 ROA using "krillc roas update --add ...", so this is an issue with the UI, not with krill per se.

**Comment by timbru** [comment]
Indeed, I can confirm that this is cross platform. I mistakenly thought this worked for safari and mac, but I was looking at the Max Length field, rather than the prefix field - the latter has the wrong limit.. will fix and include in RC3 - possibly along with some other things we find.
